name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Run tests coverage
        run: npm run test:coverage && mv .nyc_output/* /artifacts/ilc-plugins-sdk/.nyc_output

      - uses: actions/upload-artifact@v2
        with:
          name: server-side-tests-artifacts
          path: /artifacts/ilc-plugins-sdk/.nyc_output

      - name: Build
        run: npm run build
