name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Run tests coverage
        run: npm run test:coverage

      - uses: actions/upload-artifact@v3
        with:
          name: Test coverage
          path: .nyc_output

      - name: Build
        run: npm run build
